// react/imc/src/App.js
import React, {Component} from 'react';
import './App.css';
import {ImcCalculator} from './components/imc-calculator';

export class App extends Component {

	constructor() {
		super();
		this.state = {
			height: 1,
			weight: 0,
			imc: 28,
		};
	}
	async changeWeight(event) {
		const weight = +event.target.value
		const newState = {...this.state, weight}
		console.log(this.state)
		console.log(newState)
		await this.setState(newState) ;
		console.log(this.state)
		await this.changeImc();
		console.log(this.state)
	}
	async changeHeight(event) {
		const height = +event.target.value
		await this.setState({...this.state, height}) ;
		await this.changeImc();
	}
	async changeImc() {
		const imc = this.state.weight / (this.state.height ** 2);
		await this.setState({...this.state, imc}) ;
	}

	render() {
		return (
            <div>
		      <h1>Calcule seu IMC</h1>
		      <ImcCalculator
				imc={this.state.imc}
				onChangeWeight={(evt) => this.changeWeight(evt)}
				onChangeHeight={(evt) => this.changeHeight(evt)}
				></ImcCalculator>
		    </div>
		);
	}
}

export default App;

// vue-js/src/App.vue
<template>
  <div>
    <h1>Calcule seu IMC</h1>
    <label>Seu Peso:
      <input
        autofocus
        type="number"
        step="0.1"
        @keyup="changeWeight($event.target.value)"
      >
    </label>
    <label>Sua Altura:
      <input
        type="number"
        step="0.1"
        @keyup="changeHeight($event.target.value)"
      >
    </label>
    <span>Seu IMC é: {{imc}}</span>
  </div>
</template>

<script>
  export default {
    name: 'app',
    data() {
      return {
        weight: 0,
        height: 1,
      };
    },
    computed: {
      imc() {
        return this.weight / (this.height ** 2);
      },
    },
    methods: {
      changeWeight: function (weight) {
        this.weight = weight;
      },
      changeHeight: function (height) {
        this.height = height;
      },
    },
  };
</script>

<style>
  body {
    padding: 20px;
  }
</style>
